window.IG_DATA = {
  "account": "@teslenko_mv",
  "generated_at": "29.07.2026 00:00 МСК",
  "followers": 11,
  "days": [
    {
      "day": "2026-07-21",
      "followers": 8,
      "media_count": 1,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 2,
      "comments": 0,
      "saved": 0
    },
    {
      "day": "2026-07-22",
      "followers": 9,
      "media_count": 2,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 6,
      "comments": 0,
      "saved": 3
    },
    {
      "day": "2026-07-23",
      "followers": 10,
      "media_count": 3,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 10,
      "comments": 0,
      "saved": 5
    },
    {
      "day": "2026-07-24",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 14,
      "comments": 0,
      "saved": 6
    },
    {
      "day": "2026-07-25",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 17,
      "comments": 1,
      "saved": 7
    },
    {
      "day": "2026-07-26",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 17,
      "comments": 1,
      "saved": 8
    },
    {
      "day": "2026-07-27",
      "followers": 10,
      "media_count": 5,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 19,
      "comments": 1,
      "saved": 14
    },
    {
      "day": "2026-07-28",
      "followers": 11,
      "media_count": 7,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 23,
      "comments": 1,
      "saved": 24
    }
  ],
  "posts": [
    {
      "date": "2026-07-28",
      "date_human": "28.07.2026",
      "title": "Первая часть была о том, что включается с 1 сентября и поче…",
      "reach": 10,
      "views": 28,
      "likes": 2,
      "comments": 0,
      "saved": 1,
      "shares": 1,
      "interactions": 7,
      "er": 0.7,
      "permalink": "https://www.instagram.com/p/DbV7KVYCqwk/"
    },
    {
      "date": "2026-07-28",
      "date_human": "28.07.2026",
      "title": "Оборот 12 млн в месяц, а бизнес забирал деньги на каждой пр…",
      "reach": 13,
      "views": 46,
      "likes": 1,
      "comments": 0,
      "saved": 2,
      "shares": 2,
      "interactions": 8,
      "er": 0.6154,
      "permalink": "https://www.instagram.com/p/DbU9WtmDus2/"
    },
    {
      "date": "2026-07-27",
      "date_human": "27.07.2026",
      "title": "С 1 сентября начинается первая волна цифрового рубля. Не по…",
      "reach": 65,
      "views": 168,
      "likes": 3,
      "comments": 0,
      "saved": 3,
      "shares": 4,
      "interactions": 13,
      "er": 0.2,
      "permalink": "https://www.instagram.com/p/DbTX6cOkZaS/"
    },
    {
      "date": "2026-07-25",
      "date_human": "25.07.2026",
      "title": "Если твой товар был на сгоревшем складе — у нас есть подроб…",
      "reach": 23,
      "views": 57,
      "likes": 2,
      "comments": 1,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 0.4348,
      "permalink": "https://www.instagram.com/reel/DbNexvuFad7/"
    },
    {
      "date": "2026-07-24",
      "date_human": "24.07.2026",
      "title": "Весь разбор — в карусели. Если склад полный, а касса пустая…",
      "reach": 29,
      "views": 78,
      "likes": 5,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 14,
      "er": 0.4828,
      "permalink": "https://www.instagram.com/p/DbK0_H2Dslw/"
    },
    {
      "date": "2026-07-23",
      "date_human": "23.07.2026",
      "title": "Пожар на складах WB — удар не по «коробкам», а по деньгам с…",
      "reach": 28,
      "views": 82,
      "likes": 4,
      "comments": 0,
      "saved": 4,
      "shares": 2,
      "interactions": 13,
      "er": 0.4643,
      "permalink": "https://www.instagram.com/p/DbIbOX4jkBM/"
    },
    {
      "date": "2026-07-22",
      "date_human": "22.07.2026",
      "title": "Если твой товар был на сгоревшем складе — у нас есть подроб…",
      "reach": 25,
      "views": 97,
      "likes": 3,
      "comments": 0,
      "saved": 3,
      "shares": 4,
      "interactions": 13,
      "er": 0.52,
      "permalink": "https://www.instagram.com/p/DbGMkK2Du1L/"
    },
    {
      "date": "2026-07-21",
      "date_human": "21.07.2026",
      "title": "Убили 49 товаров из 50 — и клиент вырос в 4 раза.",
      "reach": 329,
      "views": 562,
      "likes": 3,
      "comments": 0,
      "saved": 5,
      "shares": 4,
      "interactions": 15,
      "er": 0.0456,
      "permalink": "https://www.instagram.com/p/DbDuLm9jn2V/"
    }
  ]
};
