window.IG_DATA = {
  "account": "@teslenko_mv",
  "generated_at": "22.08.2026 00:00 МСК",
  "followers": 18,
  "days": [
    {
      "day": "2026-07-21",
      "followers": 8,
      "media_count": 1,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 2,
      "comments": 0,
      "saved": 0
    },
    {
      "day": "2026-07-22",
      "followers": 9,
      "media_count": 2,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 6,
      "comments": 0,
      "saved": 3
    },
    {
      "day": "2026-07-23",
      "followers": 10,
      "media_count": 3,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 10,
      "comments": 0,
      "saved": 5
    },
    {
      "day": "2026-07-24",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 14,
      "comments": 0,
      "saved": 6
    },
    {
      "day": "2026-07-25",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 17,
      "comments": 1,
      "saved": 7
    },
    {
      "day": "2026-07-26",
      "followers": 10,
      "media_count": 4,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 17,
      "comments": 1,
      "saved": 8
    },
    {
      "day": "2026-07-27",
      "followers": 10,
      "media_count": 5,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 19,
      "comments": 1,
      "saved": 14
    },
    {
      "day": "2026-07-28",
      "followers": 11,
      "media_count": 7,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 23,
      "comments": 1,
      "saved": 24
    },
    {
      "day": "2026-07-29",
      "followers": 12,
      "media_count": 8,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 28,
      "comments": 6,
      "saved": 36
    },
    {
      "day": "2026-07-30",
      "followers": 12,
      "media_count": 9,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 30,
      "comments": 6,
      "saved": 40
    },
    {
      "day": "2026-07-31",
      "followers": 13,
      "media_count": 10,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 36,
      "comments": 13,
      "saved": 43
    },
    {
      "day": "2026-08-01",
      "followers": 13,
      "media_count": 11,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 39,
      "comments": 14,
      "saved": 45
    },
    {
      "day": "2026-08-02",
      "followers": 15,
      "media_count": 12,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 42,
      "comments": 15,
      "saved": 47
    },
    {
      "day": "2026-08-03",
      "followers": 15,
      "media_count": 13,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 43,
      "comments": 15,
      "saved": 47
    },
    {
      "day": "2026-08-04",
      "followers": 15,
      "media_count": 14,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 47,
      "comments": 15,
      "saved": 52
    },
    {
      "day": "2026-08-05",
      "followers": 15,
      "media_count": 15,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 51,
      "comments": 15,
      "saved": 61
    },
    {
      "day": "2026-08-06",
      "followers": 15,
      "media_count": 17,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 54,
      "comments": 15,
      "saved": 65
    },
    {
      "day": "2026-08-07",
      "followers": 15,
      "media_count": 19,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 56,
      "comments": 15,
      "saved": 69
    },
    {
      "day": "2026-08-08",
      "followers": 15,
      "media_count": 21,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 63,
      "comments": 15,
      "saved": 77
    },
    {
      "day": "2026-08-09",
      "followers": 17,
      "media_count": 23,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 67,
      "comments": 15,
      "saved": 94
    },
    {
      "day": "2026-08-10",
      "followers": 17,
      "media_count": 25,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 72,
      "comments": 15,
      "saved": 98
    },
    {
      "day": "2026-08-11",
      "followers": 17,
      "media_count": 26,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 72,
      "comments": 15,
      "saved": 100
    },
    {
      "day": "2026-08-12",
      "followers": 18,
      "media_count": 28,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 75,
      "comments": 15,
      "saved": 107
    },
    {
      "day": "2026-08-13",
      "followers": 18,
      "media_count": 30,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 79,
      "comments": 15,
      "saved": 113
    },
    {
      "day": "2026-08-14",
      "followers": 18,
      "media_count": 32,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 79,
      "comments": 15,
      "saved": 116
    },
    {
      "day": "2026-08-15",
      "followers": 19,
      "media_count": 35,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 99,
      "comments": 15,
      "saved": 125
    },
    {
      "day": "2026-08-16",
      "followers": 19,
      "media_count": 37,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 103,
      "comments": 16,
      "saved": 128
    },
    {
      "day": "2026-08-17",
      "followers": 19,
      "media_count": 39,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 106,
      "comments": 16,
      "saved": 136
    },
    {
      "day": "2026-08-18",
      "followers": 19,
      "media_count": 40,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 106,
      "comments": 16,
      "saved": 139
    },
    {
      "day": "2026-08-19",
      "followers": 19,
      "media_count": 42,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 113,
      "comments": 16,
      "saved": 148
    },
    {
      "day": "2026-08-20",
      "followers": 18,
      "media_count": 46,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 125,
      "comments": 18,
      "saved": 152
    },
    {
      "day": "2026-08-21",
      "followers": 18,
      "media_count": 49,
      "reach_day": null,
      "reach_followers": null,
      "reach_nonfollowers": null,
      "likes": 143,
      "comments": 18,
      "saved": 163
    }
  ],
  "posts": [
    {
      "date": "2026-08-21",
      "date_human": "21.08.2026",
      "title": "Вы правите цены руками раз в неделю, когда доходят руки. У…",
      "reach": 5,
      "views": 18,
      "likes": 1,
      "comments": 0,
      "saved": 0,
      "shares": 0,
      "interactions": 2,
      "er": 0.4,
      "permalink": "https://www.instagram.com/p/DcTwaGZjroZ/"
    },
    {
      "date": "2026-08-21",
      "date_human": "21.08.2026",
      "title": "Склады восстановят — вопрос выживания площадки можно закрыв…",
      "reach": 138,
      "views": 156,
      "likes": 5,
      "comments": 0,
      "saved": 2,
      "shares": 5,
      "interactions": 15,
      "er": 0.1087,
      "permalink": "https://www.instagram.com/reel/DcTZSNIE980/"
    },
    {
      "date": "2026-08-21",
      "date_human": "21.08.2026",
      "title": "Остатки выбиты, оборотных денег не хватает, маржинальность…",
      "reach": 120,
      "views": 146,
      "likes": 5,
      "comments": 0,
      "saved": 3,
      "shares": 4,
      "interactions": 15,
      "er": 0.125,
      "permalink": "https://www.instagram.com/reel/DcS-Ay3iMou/"
    },
    {
      "date": "2026-08-20",
      "date_human": "20.08.2026",
      "title": "Вопрос, который весь месяц висел над рынком, закрыт: склады…",
      "reach": 144,
      "views": 172,
      "likes": 7,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 16,
      "er": 0.1111,
      "permalink": "https://www.instagram.com/reel/DcRoGw4ERrc/"
    },
    {
      "date": "2026-08-20",
      "date_human": "20.08.2026",
      "title": "Месяц продавцы обсуждали один вопрос: выстоит ли площадка.…",
      "reach": 15,
      "views": 38,
      "likes": 4,
      "comments": 0,
      "saved": 2,
      "shares": 2,
      "interactions": 10,
      "er": 0.6667,
      "permalink": "https://www.instagram.com/p/DcRJnYyl6EY/"
    },
    {
      "date": "2026-08-20",
      "date_human": "20.08.2026",
      "title": "Часть вашего ассортимента работает в минус, и платите вы за…",
      "reach": 146,
      "views": 177,
      "likes": 4,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 13,
      "er": 0.089,
      "permalink": "https://www.instagram.com/reel/DcQ0eyEDAZh/"
    },
    {
      "date": "2026-08-20",
      "date_human": "20.08.2026",
      "title": "Вы всё сделали правильно: образование, карьера, ипотека, ку…",
      "reach": 9,
      "views": 21,
      "likes": 1,
      "comments": 0,
      "saved": 2,
      "shares": 2,
      "interactions": 5,
      "er": 0.5556,
      "permalink": "https://www.instagram.com/p/DcQf-NSjoG5/"
    },
    {
      "date": "2026-08-19",
      "date_human": "19.08.2026",
      "title": "Когда маржа тонкая, проще всего решить, что виноват маркетп…",
      "reach": 211,
      "views": 246,
      "likes": 7,
      "comments": 1,
      "saved": 3,
      "shares": 4,
      "interactions": 18,
      "er": 0.0853,
      "permalink": "https://www.instagram.com/reel/DcOdVZHk8te/"
    },
    {
      "date": "2026-08-19",
      "date_human": "19.08.2026",
      "title": "Комиссию площадка удержала раньше, чем деньги дошли до вас,…",
      "reach": 10,
      "views": 34,
      "likes": 1,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 9,
      "er": 0.9,
      "permalink": "https://www.instagram.com/p/DcN6vyODrTk/"
    },
    {
      "date": "2026-08-18",
      "date_human": "18.08.2026",
      "title": "Ваша прибыль на Wildberries уже считается по новым правилам…",
      "reach": 10,
      "views": 43,
      "likes": 1,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 1.0,
      "permalink": "https://www.instagram.com/p/DcLPgQ3DqLh/"
    },
    {
      "date": "2026-08-17",
      "date_human": "17.08.2026",
      "title": "Вы каждый месяц докладываете в магазин свои деньги и говори…",
      "reach": 10,
      "views": 33,
      "likes": 1,
      "comments": 1,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 1.0,
      "permalink": "https://www.instagram.com/p/DcJbdJEDsMc/"
    },
    {
      "date": "2026-08-17",
      "date_human": "17.08.2026",
      "title": "Вы читаете «мы ценим вашу приватность» в соглашении на шест…",
      "reach": 23,
      "views": 53,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.4783,
      "permalink": "https://www.instagram.com/p/DcIqsqvjv6V/"
    },
    {
      "date": "2026-08-16",
      "date_human": "16.08.2026",
      "title": "Пока вы неделю собираете карточку, сосед по нише успевает п…",
      "reach": 7,
      "views": 24,
      "likes": 1,
      "comments": 0,
      "saved": 1,
      "shares": 1,
      "interactions": 5,
      "er": 0.7143,
      "permalink": "https://www.instagram.com/p/DcG19uCDpXT/"
    },
    {
      "date": "2026-08-16",
      "date_human": "16.08.2026",
      "title": "Экран, который смотрит на вас, вы купили сами — и платите з…",
      "reach": 12,
      "views": 23,
      "likes": 1,
      "comments": 0,
      "saved": 1,
      "shares": 1,
      "interactions": 5,
      "er": 0.4167,
      "permalink": "https://www.instagram.com/p/DcGF5-0jsDp/"
    },
    {
      "date": "2026-08-15",
      "date_human": "15.08.2026",
      "title": "С вас уже списывают за страховку, которую вы не подключали:…",
      "reach": 16,
      "views": 54,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.6875,
      "permalink": "https://www.instagram.com/p/DcERLa1jsHI/"
    },
    {
      "date": "2026-08-15",
      "date_human": "15.08.2026",
      "title": "Из пятидесяти позиций деньги приносила одна. Владелец не зн…",
      "reach": 216,
      "views": 275,
      "likes": 9,
      "comments": 1,
      "saved": 4,
      "shares": 4,
      "interactions": 20,
      "er": 0.0926,
      "permalink": "https://www.instagram.com/reel/DcD8XGXCZkT/"
    },
    {
      "date": "2026-08-15",
      "date_human": "15.08.2026",
      "title": "Ваш покупатель не исчез. Он уже купил — у того, чей товар л…",
      "reach": 17,
      "views": 52,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.6471,
      "permalink": "https://www.instagram.com/p/DcDhG36DohP/"
    },
    {
      "date": "2026-08-14",
      "date_human": "14.08.2026",
      "title": "Оборот 5,5 млн в месяц, заказы каждый день, склад полный —…",
      "reach": 13,
      "views": 32,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.8462,
      "permalink": "https://www.instagram.com/p/DcBsYAxDkt_/"
    },
    {
      "date": "2026-08-14",
      "date_human": "14.08.2026",
      "title": "Bloomberg пишет: власти обсуждают, чтобы отдать склады «Поч…",
      "reach": 29,
      "views": 74,
      "likes": 1,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 0.3448,
      "permalink": "https://www.instagram.com/p/DcA8Totjt69/"
    },
    {
      "date": "2026-08-13",
      "date_human": "13.08.2026",
      "title": "Прибыль в голове всегда больше, чем на счёте, и разница обы…",
      "reach": 12,
      "views": 46,
      "likes": 1,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 0.8333,
      "permalink": "https://www.instagram.com/p/Db_HnjSjgcR/"
    },
    {
      "date": "2026-08-13",
      "date_human": "13.08.2026",
      "title": "Wildberries зовёт предпринимателей открывать склады от 200…",
      "reach": 13,
      "views": 35,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.8462,
      "permalink": "https://www.instagram.com/p/Db-XgpNDmOK/"
    },
    {
      "date": "2026-08-12",
      "date_human": "12.08.2026",
      "title": "Свобода сегодня выглядит просто: уехать из города, купить з…",
      "reach": 24,
      "views": 58,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 0.4583,
      "permalink": "https://www.instagram.com/p/Db87NBTDuvj/"
    },
    {
      "date": "2026-08-12",
      "date_human": "12.08.2026",
      "title": "Когда рынок пересобирается, сильные первыми снижают активно…",
      "reach": 10,
      "views": 29,
      "likes": 2,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 11,
      "er": 1.1,
      "permalink": "https://www.instagram.com/p/Db8HV0ljuOy/"
    },
    {
      "date": "2026-08-11",
      "date_human": "11.08.2026",
      "title": "Пять чисел на единицу товара решают, зарабатываете вы на нё…",
      "reach": 11,
      "views": 33,
      "likes": 1,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 10,
      "er": 0.9091,
      "permalink": "https://www.instagram.com/p/Db6UG45jmDC/"
    },
    {
      "date": "2026-08-10",
      "date_human": "10.08.2026",
      "title": "Ваш товар уже продаётся на AliExpress — и вы об этом, скоре…",
      "reach": 13,
      "views": 34,
      "likes": 3,
      "comments": 0,
      "saved": 3,
      "shares": 3,
      "interactions": 12,
      "er": 0.9231,
      "permalink": "https://www.instagram.com/p/Db3bQzmjgCg/"
    }
  ]
};
